language: python
python:
    - "2.7"

install: pip install -r requirements/dev.txt

before_install:
    - echo "Fetching and installing BLAST"
    - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.26/ncbi-blast-2.2.26+-x64-linux.tar.gz
    - tar -zxvf ncbi-blast-2.2.26+-x64-linux.tar.gz | tail
    - export PATH="${TRAVIS_BUILD_DIR}/ncbi-blast-2.2.26+/bin:$PATH"

script:  nosetests --verbosity 2 --cover-html --with-coverage tests --cover-package=pyphylogenomics

after_success: coveralls